In [3]:
import numpy as np

## array in np
- 和一般的的array不一樣點在 type 不同
- 號稱計算較快
- list加載元件較快
- 沒有","

In [29]:
np_array = np.array([[1,2,3],[4,3,2]])
np_array_2dim = np.array([(2.5, 1, 3, 4.5), (5, 6, 7, 8)], dtype = float)  # np.int(int)  
array = [[1,2,3],[4,3,2]]

In [30]:
print(np_array)

print('--------------------')

print(np_array_2dim)
print('type is ',np_array_2dim.dtype)

print('--------------------')

print(array)

[[1 2 3]
 [4 3 2]]
--------------------
[[2 1 3 4]
 [5 6 7 8]]
type is  int32
--------------------
[[1, 2, 3], [4, 3, 2]]


In [25]:
print('number of dim:', np_array.ndim)

number of dim: 2


In [26]:
print('shape:', np_array.shape)
print(matrix.shape[1])

shape: (2, 3)
3


In [27]:
print('size:', np_array.size)

size: 6


In [40]:
# 建立一個2x3全為0的陣列    np.zeros(shape, dtye=float, order='C')
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [41]:
# 建立一個2x3x4全為1的陣列
print(np.ones((2, 3, 4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [75]:
# 建立空矩陣(接近0的矩陣)
print(np.empty((2,3), dtype = np.float16))

[[-6.188e+00 -1.417e+03  8.464e-06]
 [ 0.000e+00  0.000e+00  0.000e+00]]


In [50]:
# 建立一個由1開始，不超過10，間隔值為2的均勻數值陣列
print(np.arange(1, 10, 2))
# 和 range 一樣 range(start, end, step)

[1 3 5 7 9]


In [68]:
# 重新組結構
a = np.arange(12)
print(a)

print('--------------------')

print(a.reshape((4,3)))

print('--------------------')

print(a.reshape((-1,4)))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
# 建立一個0到10之間，均勻的5個數值陣列
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [45]:
# 建立一個3x2全為8的陣列
print(np.full((3,2), 8)) 

[[8 8]
 [8 8]
 [8 8]]


In [47]:
# 建立一個5x5的單位矩陣
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [48]:
# 建立一個2x3的隨機值矩陣
np.random.random((2,3))

array([[0.55344156, 0.01092342, 0.04289472],
       [0.43239911, 0.16730298, 0.70444857]])